import { current } from "@reduxjs/toolkit";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import styles from "../../styles/Home.module.css";
import { RootState } from "../store";
import {
  addLanguages,
  toFavorite,
  removeLanguages,
} from "../store/feature/languageSlice";
// importar SEMPRE o RootState

const Home: NextPage = () => {
  const [languages, setLanguages] = useState("");

  const language = useSelector((state: RootState) => state.languages);

  const dispatch = useDispatch();

  return (
    <div className={styles.container}>
      <Head>
        <title>redux</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <span>Next.js + RDK!</span>
        </h1>

        <div className={styles.grid}>
          {language.map((current, index) => {
            return (
              <div
                style={{
                  display: "flex",
                  width: "200px",
                  justifyContent: "space-around",
                }}
                key={index}
              >
                <span style={{ color: current.favorite ? "green" : "white" }}>
                  {current.name}
                </span>
                <button onClick={() => dispatch(toFavorite(index))}>
                  {current.favorite ? "Desfavoritar" : "favoritar"}
                </button>
                <button onClick={() => dispatch(removeLanguages(index))}>
                  x
                </button>
              </div>
            );
          })}
        </div>
        <div>
          <input
            type="text"
            value={languages}
            onChange={(e) => setLanguages(e.target.value)}
          />
          <button
            onClick={() => dispatch(addLanguages(languages))}
            type="button"
          >
            adicionar linguagem
          </button>
        </div>
      </main>
    </div>
  );
};

export default Home;
